/**
 * Shared helpers for PM export routes.
 * PDF = print-optimised HTML opened in a new tab (no Puppeteer needed).
 * XLSX = binary generated by the existing zero-dep @/lib/xlsx module.
 */
import { createXlsxWorkbook } from '@/lib/xlsx';
import { inr, ddmmyyyy } from '@/lib/project-management';

export { inr, ddmmyyyy };

export const COMPANY = 'Zentrix';

export function xlsxResponse(rows, filename, sheetName = 'Report') {
  const wb = createXlsxWorkbook(rows, sheetName.slice(0, 31));
  return new Response(wb, {
    status: 200,
    headers: {
      'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'Content-Disposition': `attachment; filename="${filename}.xlsx"`,
    },
  });
}

export function pdfHtmlResponse(title, filters, bodyHtml, filename) {
  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${escHtml(title)}</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:'Segoe UI',Arial,sans-serif;font-size:11px;color:#111;background:#fff}
h1{font-size:16px;margin-bottom:4px}
h2{font-size:13px;margin:14px 0 6px;border-bottom:1px solid #ccc;padding-bottom:3px}
.header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:12px;border-bottom:2px solid #1e40af;padding-bottom:8px}
.company{font-size:18px;font-weight:700;color:#1e40af}
.meta{font-size:10px;color:#555}
.filters{font-size:10px;background:#f1f5f9;padding:5px 8px;border-radius:4px;margin-bottom:10px;color:#374151}
table{width:100%;border-collapse:collapse;margin-bottom:10px}
th{background:#1e40af;color:#fff;text-align:left;padding:5px 7px;font-size:10px;font-weight:600}
td{padding:4px 7px;border-bottom:1px solid #e5e7eb;font-size:10px;vertical-align:top}
tr:nth-child(even) td{background:#f8fafc}
.num{text-align:right}
.total-row td{font-weight:700;background:#eff6ff!important;border-top:2px solid #1e40af}
.badge{display:inline-block;padding:1px 6px;border-radius:3px;font-size:9px;font-weight:700}
.badge-green{background:#dcfce7;color:#166534}
.badge-red{background:#fee2e2;color:#991b1b}
.badge-blue{background:#dbeafe;color:#1e40af}
.no-print{margin-bottom:12px}
@media print{.no-print{display:none!important}}
</style>
</head>
<body>
<div class="no-print">
  <button onclick="window.print()" style="padding:6px 18px;background:#1e40af;color:#fff;border:0;border-radius:4px;cursor:pointer;font-size:12px;font-weight:600">
    🖨 Print / Save as PDF
  </button>
</div>
<div class="header">
  <div>
    <div class="company">${escHtml(COMPANY)}</div>
    <h1>${escHtml(title)}</h1>
  </div>
  <div class="meta">Generated: ${ddmmyyyy(new Date())}&nbsp;|&nbsp;${new Date().toLocaleTimeString('en-IN', { hour12: true })}</div>
</div>
${filters ? `<div class="filters"><b>Filters applied:</b> ${escHtml(filters)}</div>` : ''}
${bodyHtml}
</body>
</html>`;

  return new Response(html, {
    status: 200,
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Content-Disposition': `inline; filename="${filename}.html"`,
    },
  });
}

export function escHtml(str) {
  return String(str ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

export function tableHtml(headers, rows, totalsRow = null) {
  const ths = headers.map(h => `<th${h.num ? ' class="num"' : ''}>${escHtml(h.label)}</th>`).join('');
  const trs = rows.map(row =>
    '<tr>' + headers.map(h => {
      const val = row[h.key] ?? '';
      return `<td${h.num ? ' class="num"' : ''}>${escHtml(val)}</td>`;
    }).join('') + '</tr>'
  ).join('');
  const foot = totalsRow
    ? '<tr class="total-row">' + headers.map(h => `<td${h.num ? ' class="num"' : ''}>${escHtml(totalsRow[h.key] ?? '')}</td>`).join('') + '</tr>'
    : '';
  return `<table><thead><tr>${ths}</tr></thead><tbody>${trs}${foot}</tbody></table>`;
}
