'use client';

import { useCallback, useEffect, useState } from 'react';

const date = (value) => value ? new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—';
const money = (value) => `₹${Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`;

function DetailList({ title, rows, render, empty = 'No records.', error = '' }) {
  return <section><h3 className="mb-2 font-bold">{title}</h3>{rows?.length ? <div className="space-y-2 text-sm">{rows.map((row, i) => <div className="border p-2" key={row.id || i}>{render(row)}</div>)}</div> : <p className={`text-sm ${error ? 'text-amber-600' : 'text-zinc-500'}`}>{error || empty}</p>}</section>;
}

function DetailSkeleton({ user, muted }) {
  return <div className="mt-5 space-y-5 animate-pulse"><div className="grid gap-2 text-sm sm:grid-cols-2"><p><b>Phone:</b> {user.phone || '—'}</p><p><b>Delivery city:</b> {user.delivery_city || 'No city set'}</p><p className={muted}>Loading signup and login activity…</p></div><div><h3 className="mb-2 font-bold">Order history</h3><div className="h-10 w-full bg-zinc-200 dark:bg-zinc-800" /></div><div><h3 className="mb-2 font-bold">Coupon usage</h3><div className="h-10 w-3/4 bg-zinc-200 dark:bg-zinc-800" /></div><div><h3 className="mb-2 font-bold">Moderation history</h3><div className="h-10 w-1/2 bg-zinc-200 dark:bg-zinc-800" /></div></div>;
}

export default function UserManagementAdmin({ isDarkMode }) {
  const [users, setUsers] = useState([]), [cities, setCities] = useState([]), [loading, setLoading] = useState(true), [notice, setNotice] = useState(''), [page, setPage] = useState(1), [pagination, setPagination] = useState({ page: 1, total: 0, totalPages: 0 });
  const [filters, setFilters] = useState({ search: '', status: 'all', city: '', from: '', to: '' });
  const [selected, setSelected] = useState(null), [details, setDetails] = useState(null), [detailError, setDetailError] = useState(''), [blockTarget, setBlockTarget] = useState(null), [reason, setReason] = useState(''), [saving, setSaving] = useState(false);
  const headers = () => { const token = localStorage.getItem('admin-token') || localStorage.getItem('token'); return token ? { Authorization: `Bearer ${token}` } : {}; };
  const load = useCallback(async () => { setLoading(true); try { const query = new URLSearchParams(Object.entries({ ...filters, page, pageSize: 25 }).filter(([, value]) => value !== '')); const response = await fetch(`/api/admin/users?${query}`, { headers: headers(), cache: 'no-store' }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error || 'Could not load users'); setUsers(data.data || []); setCities(data.cities || []); setPagination(data.pagination || { page: 1, total: data.data?.length || 0, totalPages: 1 }); } catch (error) { setNotice(error.message); } finally { setLoading(false); } }, [filters, page]);
  useEffect(() => { const timeout = setTimeout(load, 250); return () => clearTimeout(timeout); }, [load]);
  const openDetails = async (user) => { setSelected(user); setDetails(null); setDetailError(''); try { const response = await fetch(`/api/admin/users/${user.id}`, { headers: headers() }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error || 'Could not load details'); setDetails(data.data); } catch (error) { setDetailError(error.message || 'Unable to load user details.'); setNotice(error.message || 'Unable to load user details.'); } };
  const changeStatus = async (user, action) => { setSaving(true); try { const response = await fetch(`/api/admin/users/${user.id}/${action}`, { method: 'POST', headers: { ...headers(), 'Content-Type': 'application/json' }, body: JSON.stringify({ reason }) }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error || `Could not ${action} user`); setSelected(null); setDetails(null); setBlockTarget(null); setReason(''); setNotice(`User ${action}ed successfully.`); await load(); } catch (error) { setNotice(error.message || `Could not ${action} user`); } finally { setSaving(false); } };
  const card = isDarkMode ? 'bg-zinc-950 border-zinc-800 text-white' : 'bg-white border-zinc-200 text-zinc-900';
  const muted = isDarkMode ? 'text-zinc-400' : 'text-zinc-500';
  const updateFilters = (next) => { setPage(1); setFilters(next); };
  return <section className="p-4 md:p-7 space-y-5"><div><h1 className="text-2xl font-black">Users</h1><p className={muted}>Customer accounts, order activity, and moderation history.</p></div>{notice && <p className={`border p-3 text-sm ${card}`}>{notice}</p>}
    <div className={`border p-4 grid gap-3 md:grid-cols-5 ${card}`}><input className="border p-2 text-sm text-black" placeholder="Search name, email, phone" value={filters.search} onChange={(e) => updateFilters({ ...filters, search: e.target.value })} /><select className="border p-2 text-sm text-black" value={filters.status} onChange={(e) => updateFilters({ ...filters, status: e.target.value })}><option value="all">All statuses</option><option value="active">Active</option><option value="blocked">Blocked</option></select><select className="border p-2 text-sm text-black" value={filters.city} onChange={(e) => updateFilters({ ...filters, city: e.target.value })}><option value="">All cities</option>{cities.map((city) => <option key={city}>{city}</option>)}</select><input className="border p-2 text-sm text-black" type="date" value={filters.from} onChange={(e) => updateFilters({ ...filters, from: e.target.value })} /><input className="border p-2 text-sm text-black" type="date" value={filters.to} onChange={(e) => updateFilters({ ...filters, to: e.target.value })} /></div>
    <div className={`border overflow-x-auto ${card}`}><table className="w-full min-w-[1050px] text-sm"><thead className={isDarkMode ? 'bg-zinc-900' : 'bg-zinc-50'}><tr className="text-left"><th className="p-3">User</th><th className="p-3">Phone / city</th><th className="p-3">Signed up</th><th className="p-3">Last login</th><th className="p-3">Orders</th><th className="p-3">Lifetime spend</th><th className="p-3">Status</th><th className="p-3">Actions</th></tr></thead><tbody>{loading ? <tr><td colSpan="8" className="p-6 text-center">Loading users…</td></tr> : users.length ? users.map((user) => <tr key={user.id} className="border-t border-zinc-200 dark:border-zinc-800"><td className="p-3"><b>{user.name || 'Unnamed user'}</b><br /><span className={muted}>{user.email}</span></td><td className="p-3">{user.phone || '—'}<br /><span className={muted}>{user.delivery_city || 'No city set'}</span></td><td className="p-3">{date(user.created_at)}</td><td className="p-3">{date(user.last_login_at)}</td><td className="p-3">{user.total_orders}</td><td className="p-3">{money(user.total_spent)}</td><td className="p-3"><span className={`rounded-full px-2 py-1 text-xs font-bold ${user.is_blocked ? 'bg-red-100 text-red-700' : 'bg-green-100 text-green-700'}`}>{user.is_blocked ? 'Blocked' : 'Active'}</span></td><td className="p-3 whitespace-nowrap"><button className="mr-2 border px-2 py-1" onClick={() => openDetails(user)}>View details</button><button disabled={saving} className={`border px-2 py-1 ${user.is_blocked ? 'text-green-600' : 'text-red-600'}`} onClick={() => user.is_blocked ? changeStatus(user, 'unblock') : setBlockTarget(user)}>{user.is_blocked ? 'Unblock' : 'Block'}</button></td></tr>) : <tr><td colSpan="8" className="p-6 text-center">No users match these filters.</td></tr>}</tbody></table></div>
    <div className={`flex items-center justify-between text-sm ${muted}`}><span>{pagination.total} users · Page {pagination.page} of {pagination.totalPages || 1}</span><div className="flex gap-2"><button className="border px-3 py-1 disabled:opacity-40" disabled={loading || page <= 1} onClick={() => setPage((current) => current - 1)}>Previous</button><button className="border px-3 py-1 disabled:opacity-40" disabled={loading || !pagination.totalPages || page >= pagination.totalPages} onClick={() => setPage((current) => current + 1)}>Next</button></div></div>
    {blockTarget && <div className="fixed inset-0 z-[1001] flex items-center justify-center bg-black/60 p-4"><div className={`w-full max-w-md border p-5 ${card}`}><h2 className="text-xl font-black">Block {blockTarget.name || 'user'}?</h2><p className={`mt-2 text-sm ${muted}`}>They will be signed out on their next protected request and cannot log in, order, checkout, or use coupons.</p><textarea className="mt-4 w-full border p-2 text-black" placeholder="Optional reason, e.g. Spam orders" value={reason} onChange={(e) => setReason(e.target.value)} /><div className="mt-3 flex gap-2"><button className="border px-3 py-1" disabled={saving} onClick={() => { setBlockTarget(null); setReason(''); }}>Cancel</button><button className="border border-red-600 px-3 py-1 text-red-600" disabled={saving} onClick={() => changeStatus(blockTarget, 'block')}>{saving ? 'Blocking…' : 'Confirm block'}</button></div></div></div>}
    {selected && <div className="fixed inset-0 z-[1000] flex items-center justify-center bg-black/60 p-4"><div className={`max-h-[90vh] w-full max-w-3xl overflow-y-auto border p-5 ${card}`}><div className="flex justify-between gap-4"><div><h2 className="text-xl font-black">{selected.name || 'User details'}</h2><p className={muted}>{selected.email}</p></div><button onClick={() => { setSelected(null); setDetails(null); setDetailError(''); }}>✕</button></div>{details ? <div className="mt-5 space-y-5"><div className="grid gap-2 text-sm sm:grid-cols-2"><p><b>Phone:</b> {details.user.phone || '—'}</p><p><b>Delivery city:</b> {details.user.delivery_city || '—'}</p><p><b>Signup:</b> {date(details.user.created_at)}</p><p><b>Last login:</b> {date(details.user.last_login_at)}</p></div>{details.user.is_blocked ? <div className="border border-red-300 bg-red-50 p-3 text-red-800"><b>Currently blocked.</b> {details.user.blocked_reason || 'No reason recorded'} · {date(details.user.blocked_at)}<button className="ml-3 border border-green-600 px-2 py-1 text-green-700" onClick={() => changeStatus(selected, 'unblock')}>Unblock</button></div> : <div className="border p-3"><b>Active account</b><button className="ml-3 border border-red-600 px-3 py-1 text-red-600" onClick={() => setBlockTarget(selected)}>Block user</button></div>}<DetailList title="Order history" rows={details.orders} error={details.sectionErrors?.orders} render={(order) => <><b>{order.reference || `Order #${order.id}`}</b> · {order.description || 'Order'} · {money(order.total)} · {order.status} <span className={muted}>({date(order.created_at)})</span></>} /><DetailList title="Coupon usage" rows={details.couponUsage} error={details.sectionErrors?.coupons} empty="No coupon usage." render={(coupon) => <><b>{coupon.coupon_code}</b> · {money(coupon.coupon_discount)} discount · {coupon.order_reference} · {date(coupon.created_at)}</>} /><DetailList title="Moderation history" rows={details.moderationLog} error={details.sectionErrors?.moderation} empty="No moderation actions." render={(entry) => <><b className={entry.action === 'blocked' ? 'text-red-600' : 'text-green-600'}>{entry.action}</b> by {entry.admin_name || 'Admin'} · {entry.reason || 'No reason'} · {date(entry.created_at)}</>} /></div> : detailError ? <p className="mt-5 text-red-600">{detailError}</p> : <DetailSkeleton user={selected} muted={muted} />}</div></div>}</section>;
}
